baseURL = "/"
# Google Analytics tracking
googleAnalytics = "UA-181241343-1"

languageCode = "en-uk"
title = "Research Software Alliance"
theme = "syna"
enableGitInfo = true
version = "0.17.3"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  twitter = "https://twitter.com/researchsoft"
  github = "https://github.com/researchsoft"
  site_logo = "img/resa-logo-software-green.png"
  name = "The Research Software Alliance"

  [params.colors]
    primary = "darkgreen"
    secondary = "darkorange"

[[menu.main]]
  identifier = "/about-resa"
  name = "About"
  weight = 10
  
[[menu.main]]
  parent = "/about-resa"
  url = "/about-resa"
  name = "About"
  weight = 11

[[menu.main]]
  parent = "/about-resa"
  url = "/people"
  name = "People"
  weight = 12

[[menu.main]]
  parent = "/about-resa"
  url = "/membership"
  name = "Organisational Membership"
  weight = 13
  

[[menu.main]]
  url = "/taskforces"
  name = "Task forces"
  weight = 20

[[menu.main]]
  identifier = "/forums"
  name = "Forums"
  weight = 30
  
[[menu.main]]
  parent = "/forums"
  url = "/funders-forum"
  name = "Funders Forum"
  weight = 31

[[menu.main]]
  parent = "/forums"
  url = "../events/2022-06/"
  name = "Community Forum"
  weight = 32
  

[[menu.main]]
  identifier = "/resa-resources"
  url = "/resa-resources"
  name = "Resources"
  weight = 40

[[menu.main]]
  parent = "/resa-resources"
  name = "Resources"
  url = "/resa-resources"
  weight = 41

[[menu.main]]
  parent = "/resa-resources"
  name = "Guidelines"
  url = "/guidelines"
  weight = 42

[[menu.main]]
  url = "/news"
  name = "News"
  weight = 50

[[menu.main]]
  url = "/events"
  name = "Events"
  weight = 60

[[menu.main]]
    url = "/blog"
    name = "Blog"
    weight = 70

[[menu.footer_social]]
  weight = 20
  name = "twitter"
  url = "https://twitter.com/researchsoft"
  pre = "fab fa-twitter"

[[menu.footer_social]]
  weight = 30
  name = "github"
  url = "https://github.com/researchsoft/website"
  pre = "fab fa-github fa-stack-2x"

[[menu.footer_social]]
  weight = 40
  name = "email"
  url = "/contact/"
  pre = "fa fa-envelope"

[[menu.footer_social]]
  weight = 50
  name = "slack"
  url = "https://join.slack.com/t/researchsoft/shared_invite/zt-1flmrglww-SoWjAK_5TJyqLU_~Jx697w"
  pre = "fab fa-slack"

[[menu.copyright_footer]]
  url = "/license"
  name = "License"
  weight = 60
  color = "primary"

[[menu.copyright_footer]]
  url = "/code-of-conduct"
  name = "Code of Conduct"
  weight = 70
  color = "primary"
